### ISSUE TITLE
Global options parsing cannot be relied on to parse positional arguments correctly

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-cli#126]
If you trace how `set_policy --priority 1` is parsed it turns out to be

```
./scripts/rabbitmqctl set_policy --priority 1 federate-me "^amq." '{"federation-upstream-set":"all"}'
** (CaseClauseError) no case clause matching: {["set_policy", "federate-me", "^amq.", "{\"federation-upstream-set\":\"all\"}"], %{priority: 1}, []}
    (rabbitmqctl) lib/rabbitmqctl.ex:43: RabbitMQCtl.main/1
    (elixir) lib/kernel/cli.ex:76: anonymous fn/3 in Kernel.CLI.exec_fun/2
```

```
{"set_policy", RabbitMQ.CLI.Ctl.Commands.SetPolicyCommand, ["1", "federate-me", "^amq.", "{\"federation-upstream-set\":\"all\"}"]}
```

so the "1" argument gets treated as positional. This is wrong and breaks existing commands.

`Elixir.OptionParser`, however, is not to blame:

```

iex(4)> OptionParser.parse(["--priority=1"], switches: [priority: :integer])
{[priority: 1], [], []}
iex(5)> OptionParser.parse(["--priority", "1"], switches: [priority: :integer])
{[priority: 1], [], []}
```

**Comment by michaelklishin** [comment]
I believe this started with 9196ef719a7261d5c7e86f4087f3e9fb41e97520.

**Comment by michaelklishin** [comment]
There turns out to be a fundamental problem with https://github.com/rabbitmq/rabbitmq-cli/commit/9196ef719a7261d5c7e86f4087f3e9fb41e97520: "global" options parser cannot be relied on to parse positional arguments because it is unaware of command-specific switches and will leave extra values behind.

The only fix I could come up with in a couple of hours includes ignoring positional arguments from the global parser. This also has a downside: with that we effectively require command name to be the first argument but [rabbitmqctl(1)](https://www.rabbitmq.com/man/rabbitmqctl.1.man.html) suggests and encourages global options to be provided first :(

**Comment by michaelklishin** [comment]
I'm going to revert https://github.com/rabbitmq/rabbitmq-cli/pull/124, which fixes this.
