### ISSUE TITLE
Don't assume `Mix.env` is always available

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-cli#174]
I managed to hit this exception as part of testing https://github.com/rabbitmq/rabbitmq-server-release/issues/12 with zsh and a Debian package: 

```
ubuntu% autoload _enable_rabbitmqctl_completion; _enable_rabbitmqctl_completion
ubuntu% sudo rabbitmqctl list** (UndefinedFunctionError) function Mix.env/0 is undefined (module Mix is not available)
    Mix.env()
    (rabbitmqctl) lib/rabbitmq/cli/core/command_modules.ex:119: RabbitMQ.CLI.Core.CommandModules.command_in_scope/2
    (elixir) lib/enum.ex:814: anonymous fn/3 in Enum.filter/2
    (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:814: Enum.filter/2
    (rabbitmqctl) lib/rabbitmq/cli/core/command_modules.ex:44: RabbitMQ.CLI.Core.CommandModules.load_commands/2
    (rabbitmqctl) lib/rabbitmq/cli/core/command_modules.ex:32: RabbitMQ.CLI.Core.CommandModules.load/1
    (rabbitmqctl) lib/rabbitmq/cli/core/parser.ex:32: RabbitMQ.CLI.Core.Parser.parse/1

** (UndefinedFunctionError) function Mix.env/0 is undefined (module Mix is not available)
    Mix.env()
    (rabbitmqctl) lib/rabbitmq/cli/core/command_modules.ex:119: RabbitMQ.CLI.Core.CommandModules.command_in_scope/2
    (elixir) lib/enum.ex:814: anonymous fn/3 in Enum.filter/2
    (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:814: Enum.filter/2
    (rabbitmqctl) lib/rabbitmq/cli/core/command_modules.ex:44: RabbitMQ.CLI.Core.CommandModules.load_commands/2
    (rabbitmqctl) lib/rabbitmq/cli/core/command_modules.ex:32: RabbitMQ.CLI.Core.CommandModules.load/1
    (rabbitmqctl) lib/rabbitmq/cli/core/parser.ex:32: RabbitMQ.CLI.Core.Parser.parse/1
```

**Comment by michaelklishin** [comment]
If `Mix.env` is not available we should assume it is `production`.
