### ISSUE TITLE
"rabbitmq-plugins set" error

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-cli#241]
Reproduced using 3.7.3 generic-unix package and Erlang 20.2.3:

```
$ ./sbin/rabbitmq-plugins set --offline rabbitmq_management
The following plugins have been configured:
  rabbitmq_management
  rabbitmq_management_agent
  rabbitmq_web_dispatch
Applying plugin configuration to rabbit@shostakovich...
** (FunctionClauseError) no function clause matching in RabbitMQ.CLI.Formatters.Plugins.applying/2
    (rabbitmqctl) lib/rabbitmq/cli/formatters/plugins.ex:149: RabbitMQ.CLI.Formatters.Plugins.applying(%{mode: :offline, set: [:rabbitmq_management, :rabbitmq_management_agent, :rabbitmq_web_dispatch]}, %{formatter: "plugins", longnames: false, node: :rabbit@shostakovich, offline: true, online: false, quiet: true, timeout: :infinity})
    (elixir) lib/stream.ex:495: anonymous fn/4 in Stream.map/2
    (elixir) lib/stream.ex:876: Stream.do_transform_each/3
    (elixir) lib/stream.ex:1385: anonymous fn/3 in Enumerable.Stream.reduce/3
    (elixir) lib/stream.ex:638: anonymous fn/3 in Stream.take/2
    (elixir) lib/stream.ex:263: anonymous fn/3 in Stream.drop/2
    (elixir) lib/stream.ex:1356: Stream.do_unfold/4
    (elixir) lib/stream.ex:1405: Enumerable.Stream.do_each/4

(19.3)lbakken@shostakovich ~/issues/rmq-generic-unix/rabbitmq_server-3.7.3
$ ./sbin/rabbitmq-plugins list
 Configured: E = explicitly enabled; e = implicitly enabled
 | Status: [failed to contact rabbit@shostakovich - status not shown]
 |/
[  ] rabbitmq_amqp1_0                  3.7.3
[  ] rabbitmq_auth_backend_cache       3.7.3
[  ] rabbitmq_auth_backend_http        3.7.3
[  ] rabbitmq_auth_backend_ldap        3.7.3
[  ] rabbitmq_auth_mechanism_ssl       3.7.3
[  ] rabbitmq_consistent_hash_exchange 3.7.3
[  ] rabbitmq_event_exchange           3.7.3
[  ] rabbitmq_federation               3.7.3
[  ] rabbitmq_federation_management    3.7.3
[  ] rabbitmq_jms_topic_exchange       3.7.3
[E ] rabbitmq_management               3.7.3
[e ] rabbitmq_management_agent         3.7.3
[  ] rabbitmq_mqtt                     3.7.3
[  ] rabbitmq_peer_discovery_aws       3.7.3
[  ] rabbitmq_peer_discovery_common    3.7.3
[  ] rabbitmq_peer_discovery_consul    3.7.3
[  ] rabbitmq_peer_discovery_etcd      3.7.3
[  ] rabbitmq_peer_discovery_k8s       3.7.3
[  ] rabbitmq_random_exchange          3.7.3
[  ] rabbitmq_recent_history_exchange  3.7.3
[  ] rabbitmq_sharding                 3.7.3
[  ] rabbitmq_shovel                   3.7.3
[  ] rabbitmq_shovel_management        3.7.3
[  ] rabbitmq_stomp                    3.7.3
[  ] rabbitmq_top                      3.7.3
[  ] rabbitmq_tracing                  3.7.3
[  ] rabbitmq_trust_store              3.7.3
[e ] rabbitmq_web_dispatch             3.7.3
[  ] rabbitmq_web_mqtt                 3.7.3
[  ] rabbitmq_web_mqtt_examples        3.7.3
[  ] rabbitmq_web_stomp                3.7.3
[  ] rabbitmq_web_stomp_examples       3.7.3
```

**Comment by lukebakken** [comment]
```
** (FunctionClauseError) no function clause matching in RabbitMQ.CLI.Formatters.Plugins.applying/2    
    
    The following arguments were given to RabbitMQ.CLI.Formatters.Plugins.applying/2:
    
        # 1
        %{mode: :offline, set: [:rabbitmq_management, :rabbitmq_management_agent, :rabbitmq_web_dispatch]}
    
        # 2
        %{longnames: false, node: :rabbit@shostakovich, offline: true, online: false, timeout: :infinity}
    
    (rabbitmqctl) lib/rabbitmq/cli/formatters/plugins.ex:149: RabbitMQ.CLI.Formatters.Plugins.applying/2
    (elixir) lib/stream.ex:516: anonymous fn/4 in Stream.map/2
    (elixir) lib/stream.ex:897: Stream.do_transform_each/3
    (elixir) lib/stream.ex:1413: anonymous fn/3 in Enumerable.Stream.reduce/3
    (elixir) lib/stream.ex:660: anonymous fn/3 in Stream.take/2
    (elixir) lib/stream.ex:293: anonymous fn/3 in Stream.drop/2
    (elixir) lib/stream.ex:1384: Stream.do_unfold/4
    (elixir) lib/stream.ex:1433: Enumerable.Stream.do_each/4
```
