### ISSUE TITLE
CLI command rabbitmq-diagnostics status can't parse watermark

### ISSUE THREAD

**Issue by dreiucker** [rabbitmq/rabbitmq-cli#395]
While on RabbitMQ v3.7.15 the command executed seamlessly on RabbitMQ v3.8.2 it seems the `vm_memory_high_watermark.absolute` can not be parsed when calling `rabbitmq-diagnostics status` :

```
rabbitmq-diagnostics status
Status of node rabbit@member-0 ...
Stack trace:
** (FunctionClauseError) no function clause matching in RabbitMQ.CLI.Core.Memory.parse_watermark/1
    (rabbitmqctl) lib/rabbitmq/cli/core/memory.ex:81: RabbitMQ.CLI.Core.Memory.parse_watermark(858993459)
    (rabbitmqctl) lib/rabbitmq/cli/core/memory.ex:69: RabbitMQ.CLI.Core.Memory.formatted_watermark/1
    (rabbitmqctl) lib/rabbitmq/cli/ctl/commands/status_command.ex:205: RabbitMQ.CLI.Ctl.Commands.StatusCommand.result_map/1
    (rabbitmqctl) lib/rabbitmq/cli/ctl/commands/status_command.ex:77: RabbitMQ.CLI.Ctl.Commands.StatusCommand.output/2
    (rabbitmqctl) lib/rabbitmqctl.ex:166: RabbitMQCtl.maybe_run_command/3
    (rabbitmqctl) lib/rabbitmqctl.ex:134: anonymous fn/5 in RabbitMQCtl.do_exec_parsed_command/5
    (rabbitmqctl) lib/rabbitmqctl.ex:588: RabbitMQCtl.maybe_with_distribution/3
    (rabbitmqctl) lib/rabbitmqctl.ex:106: RabbitMQCtl.exec_command/2
Error:
:function_clause
```

We are using the same configuration on RabbitMQ v3.7.15 as in RabbitMQ v3.8.2 regards the `vm_memory_high_watermark.absolute`

**Snipped from rabbitmq.conf**
```
## Alternatively, we can set a limit (in bytes) of RAM used by the node.
##
vm_memory_high_watermark.absolute = 858993459
```

Please let me know if any other information is needed to identify the problem cause.

**Comment by lukebakken** [comment]
Thank you for taking the time to report this as well as instructions on how to reproduce 👍

**Comment by michaelklishin** [comment]
The issue is not present in `v3.7.x` because it doesn't have the new status command, and so the code path is fairly different.
